import { AnyFunc, Composed } from './types';
import type { T_qfilterAsync, T_waitTap, T_forEachParallel } from '../types/async';
/** One promise waits for another. */
export declare const forEachSerial: {
    (a: import("./curry").Placeholder, b: any[]): (a: AnyFunc) => Promise<void>;
    (a: AnyFunc, b: import("./curry").Placeholder): (b: any[]) => Promise<void>;
    (a: AnyFunc): (b: any[]) => Promise<void>;
    (a: AnyFunc, b: any[]): Promise<void>;
};
/** Promise.all wrapper for functional pipelining. */
export declare const waitAll: <T>(promises: Promise<T>[]) => Promise<Awaited<T>[]>;
/** Like waitAll but resolves early when all promises settle, filling the array with results in-place.
 * @param xs Array of promises.
 */
export declare const qwaitAll: <T>(xs: Promise<T>[]) => Promise<T[]>;
/** Waits for a Promise that been generated by the first arg, then returns an untoched value. Types T.
 * @param {AnyFunc<Promise>} fn - function to wait.
 * @param {T} s - any value to tap and return back
 * @returns {T}
 */
export declare const waitTap: T_waitTap;
/** Waits for all promises mapped by the fn. */
export declare const forEachParallel: T_forEachParallel;
/** The same as compose, but waits for promises in chains and returns a Promise.  */
export declare const composeAsync: <TIn extends any[] = any[], TOut = any>(...fns: AnyFunc[]) => Composed<TIn, Promise<TOut>>;
/**
 * @param cond async (v, k) -> boolean.
 * @param data T extends any[] | AnyObject.
 * @returns T
*/
export declare const qfilterAsync: T_qfilterAsync;
