import type { T_forEachParallel, T_qfilterAsync, T_waitTap } from '../types/async'
import { AnyFunc, Composed } from '../types/base'
import { curry2 } from './curry'
import { length, not_assigned } from './internal'
import { head, noop } from './safe'
import { isArray } from './utils'

/** One promise waits for another. */
export const forEachSerial = (() => {
  const pipe = async (fn: AnyFunc, items: any[], i: number) => {
    if(i<items.length) {
      await fn(items[i])
      await pipe(fn, items, ++i)
    }
  }
  return curry2(
    (fn: AnyFunc, items: any[]) => pipe(fn, items, 0)
  )
})()
/** Promise.all wrapper for functional pipelining. */
export const waitAll = <T>(promises: Promise<T>[]) => Promise.all<T>(promises)
/** Like waitAll but resolves early when all promises settle, filling the array with results in-place.
 * @param xs Array of promises.
 */
export const qwaitAll = async <T>(xs: Promise<T>[]) => new Promise<T[]>((ff, rj) => {
  const len = length(xs); let j = len
  for(let i=0; i<len; i++) xs[i].then((x: T) => {xs[i]=x as any; if(--j) ff(xs as any)}).catch(rj)
})
/** Waits for a Promise that been generated by the first arg, then returns an untoched value. Types T.
 * @param {AnyFunc<Promise>} fn - function to wait.
 * @param {T} s - any value to tap and return back
 * @returns {T}
 */
export const waitTap = curry2(
  async (fn: AnyFunc<Promise<any>>, s: any) => { await fn(s); return s }
) as any as T_waitTap
/** Waits for all promises mapped by the fn. */
export const forEachParallel = curry2(
  (fn: (item: any) => Promise<any>, items: any[]) => Promise.all(items.map(fn))
) as any as T_forEachParallel
/** The same as compose, but waits for promises in chains and returns a Promise.  */
export const composeAsync = (() => {
  const pipe = async (fns: AnyFunc[], input: any[], i: number): Promise<any> =>
    ~i ? await pipe(fns, [await fns[i](...input)], --i) : head(input)
  return <TIn extends any[] = any[], TOut = any>(...fns: AnyFunc[]): Composed<TIn, Promise<TOut>> =>
    (...input: any[]) => pipe(fns, input, fns.length-1)
})()
/**
 * @param cond async (v, k) -> boolean.
 * @param data T extends any[] | AnyObject.
 * @returns T
*/
export const qfilterAsync = curry2(async (
  cond: (v: any, k: string | number) => Promise<boolean> | boolean,
  data: any
): Promise<any> => {
  if(isArray(data)) {
    let indicies_offset = 0
    const indicies2rm: number[] = []
    const len = length(data as any[])
    for(let i = 0; i<len; i++)
      if(!await cond((data as any[])[i], i))
        indicies2rm.push(i)
    for(const i of indicies2rm)
      data.splice(i - indicies_offset++, 1)
  } else for(const k in data)
    if(!await cond(data[k], k)) delete data[k]
  return data
}) as any as T_qfilterAsync
// TODO: add .then(), .finally() and .catch() to return QPromise.
export class QPromise<T> extends Promise<T> {
  private ff!: AnyFunc
  private rj!: AnyFunc
  private _cancel_data: any
  public cancel(resolve = false) {
    if(resolve) this.ff?.(); else this.rj?.()
    this.oncancel(this._cancel_data)
  }
  constructor(fn: AnyFunc<any, [AnyFunc, AnyFunc, AnyFunc?]>, private oncancel = noop) {
    let _cancel_data: any = not_assigned
    super((ff, rj) => {
      _cancel_data = fn(ff, rj)
      setTimeout(() => {this.ff = ff; this.rj = rj})
    })
    const set_cb = () => this._cancel_data=_cancel_data
    // @ts-ignore-next
    if(_cancel_data!==not_assigned) set_cb()
    else setTimeout(set_cb)
  }
}